### ISSUE TITLE
BUG: Dashboard - Topic member list - Group name empty in "through a group"

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#258] opened 2019-05-08 15:25 UTC
![image](https://user-images.githubusercontent.com/7405383/57387261-aa83cc80-71be-11e9-8e19-6e806af511aa.png)

**Comment by loorm** [comment] 2019-05-20 08:15
Triage #4 - this issue is a duplicate of #260 . Closing issue.

**Closed as completed** 2019-05-20 08:16 UTC
Labels: bug, good first issue

**Comment by KatiVellak** [comment] 2020-04-06 14:24
Legally reviewed, no impact.
