### ISSUE TITLE
UX: Visual vote distribution

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#262] opened 2019-05-13 10:09 UTC
Currently, there's no visual representation of the vote distribution. 
Author/user has to read into the tiny numbers on the right-hand side of all options and compare them manually, which becomes really difficult when there's a larger number of options. 

<img width="773" alt="Screenshot 2019-05-11 at 14 56 38" src="https://user-images.githubusercontent.com/34126353/57613093-bd135280-757e-11e9-8ed9-8ee1515145f9.png">

(Plus currently there's also a bug of [incorrect visual representation in case of a tie](https://github.com/citizenos/citizenos-fe/issues/261)).

**Desired solution**
We should have the voting results represented visually, to immediately visually gauge the winning option and its advantage over the other options, without having to analyze the numbers.

I understand this has been discussed before between Mikk and Margo before, and showing votes as comparable columns of respective size has been deemed impossible, as this would break on small(-er) screens when topic has a large amount of voting options.

Perhaps we could sort results as horizontal columns, by most votes received? 

![Screenshot 2019-05-13 at 13 08 42](https://user-images.githubusercontent.com/34126353/57613734-4b3c0880-7580-11e9-9ab6-62278cfdb5bc.png)

**Comment by loorm** [comment] 2019-05-14 06:56
Queueing this for Triage #4

**Comment by loorm** [comment] 2019-05-20 07:40
Triage #4 - reproduced error. Label as bug, since we're pretty sure we had this visual representation of voting results working.

Decided not to implement top-to-bottom sorting in visual results, because user may have a deliberate order for voting options, which would then be messed up.

**Comment by tiblu** [comment] 2019-05-20 07:57
Related to and should be fixed in one go: https://github.com/citizenos/citizenos-fe/issues/261

**Comment by loorm** [comment] 2019-06-03 07:32
Triage #5 - feature is in test environment. Needs to be reviewed.

**Closed as completed** 2019-06-12 10:41 UTC
Labels: bug

**Comment by KatiVellak** [comment] 2020-04-10 12:15
Legally reviewed, no impact.

**Comment by loorm** [comment] 2020-05-21 18:42
Tested. Confirmed working.
