### ISSUE TITLE
Something missing in comment menu

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-fe-old#467] opened 2020-04-29 07:56 UTC
**What is the problem?**
There's something missing, see screenshot.

![smth_missing](https://user-images.githubusercontent.com/22661743/80572982-da4b6600-8a07-11ea-992c-a6777144cf7b.jpg)

**Why is this a problem?**
If you don't notice the rectangle, it is difficult to find edit and delete comment options.

**Possible solution.**
Replace the rectangle with whatever was supposed to be there.

**Comment by loorm** [comment] 2020-04-29 11:52
Triage 20 - change this from FontAwesome to custom graphics. Do the same for inline comments and inline votes plugins. Est dev time 4 hrs.

**Comment by tiblu** [comment] 2020-05-19 11:04
Done!

![image](https://user-images.githubusercontent.com/7405383/82319125-b614f080-99d9-11ea-9f6a-e09927ae04c4.png)

**Comment by oksks** [comment] 2020-05-19 11:24
@tiblu, 2 questions: 
1) Why do we allow editing someone else's reply btw - is that by design?
2) Why is the edit button hidden behind the 3 dots, instead of just displaying the edit button? Why is the extra click needed.. I understand if there were several options to choose from, but there's just one.

**Comment by tiblu** [comment] 2020-05-19 14:11
@oksks Appreciate the attention to detail! 

I restored the state of the UI to reflect the design as I think it was before the icon got lost.
And I cannot comment on the other issues. Maybe @ilmartyrk  can shed some light.

My thoughts tho:

> Why do we allow editing someone else's reply btw - is that by design?

Yeah, that is weird. Should not be allowed. Maybe thats how original EP comments was implemented by Etherpad? @ilmartyrk 

> Why is the edit button hidden behind the 3 dots, instead of just displaying the edit button? Why is the extra click needed.. I understand if there were several options to choose from, but there's just one.

Yeah, not consistent with the rest of the UX. I tried to find designs for the feature in Invision, but I did not find any. Maybe @ilmartyrk can comment how we came to this design.

**Comment by loorm** [comment] 2020-05-20 07:18
@kevincrepin UX discussion here. Please have a look.

**Comment by kevincrepin** [comment] 2020-05-20 10:46
Initially it was an arrow to indicate a dropdown menu. Not sure when it was turned into the kebab icon, maybe because of Etherpad :)

In any case, in our arguments section we have done some minor updates as to how we show all of this data, so I now also put these in the same line. There's an action menu that (can) open up edit, delete, report, probably not share?

https://projects.invisionapp.com/d/main#/console/9829159/301183006/preview
Let's keep this uniform and even when there is only one action available to the user because of their role, let's still keep it under the actions menu. Then the user learns about the consistent presence of actions.

**Comment by loorm** [comment] 2020-05-20 12:10
@tiblu Kevin specified the design. Re-opening the issue.

**Comment by KatiVellak** [comment] 2020-05-22 11:55
Editing someone else's reply should not be allowed. Has this been fixed?

**Comment by loorm** [comment] 2020-05-25 09:38
Triage 22. Est dev time 4 hours. Prioritizing.

**Comment by tiblu** [comment] 2020-05-27 07:51
TODO:

- [ ] Drop down menu
![image](https://user-images.githubusercontent.com/7405383/83003977-bc2d5180-a017-11ea-9718-82b4cbefb2b2.png)
- [ ] Disable editing someone elses reply IF it is possible

**Comment by tiblu** [comment] 2020-05-27 11:11
Depends on https://github.com/citizenos/citizenos-fe/issues/466

After looking into it this there is no point of doing it before #466 is done.

THEN we either:

1. Try to sync our fork with latest https://github.com/ether/ep_comments and apply new menu visuals.
2. Make a clean fork of https://github.com/ether/ep_comments and re-do the whole visual design on top.

Either way, I feel like if I implement anything right now, it would be a waste of time.

**Comment by tiblu** [comment] 2020-05-27 11:22
Created an issue to upstream on the comment/reply authorization issue - https://github.com/ether/ep_comments/issues/125

**Comment by tiblu** [comment] 2020-05-27 14:19
> Editing someone else's reply should not be allowed. Has this been fixed?

@loorm @KatiVellak  Unfortunately this is "by design", that is, this has never been a concern to other users - https://github.com/ether/ep_comments/issues/125#issuecomment-634688488

Which means, if we want this, we probably have to implement this. NO ETA, have to dig in deep.

**Comment by loorm** [comment] 2020-05-28 09:56
I can't see a way around this. Editing someone else's comments simply is not cool. We have to work on this.

**Comment by ilmartyrk** [comment] 2020-08-04 13:34
Closing it as the style has changed too much with EP 1.8.4 and editing other users comments is fixed

**Closed as completed by ilmartyrk** 2020-08-04 13:34 UTC
Labels: bug, UX, etherpad
