### ISSUE TITLE
Dashboard - /my/topics/:topicId - parameter openTabs will not open the listed tabs on load

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#291] opened 2019-10-16 12:03 UTC
**What is the problem?**

* Open up a Topic on the dashboard with a direct link. For example DEV LINK - https://dev.citizenos.com:3001/en/my/topics/7269dd63-1487-42a9-a736-79c7a2474d25?filter=all&openTabs=user_list

Issues:

* User list is not open when page loads 
* When you click to expand the User list, the parameter "openTabs" is removed from the url, but the list still does not open. Second click on expand will actually open the list.

![image](https://user-images.githubusercontent.com/7405383/66917428-041ddc00-f026-11e9-8217-abf3e5041786.png)

Related to:

* #112 - found the issue while working on this

**Comment by loorm** [comment] 2019-10-21 08:23
Triage 13 - designate low priority, due to rare use case (copy-pasteing dashboard URL)

**Comment by KatiVellak** [comment] 2020-04-10 15:00
Legally reviewed, no impact.

**Comment by ilmartyrk** [comment] 2021-03-15 09:35
Can't reproduce, seems to have been fixed by some other update possibly paginating users and groups

**Closed as completed by ilmartyrk** 2021-03-15 09:35 UTC
Labels: bug, UX
