### ISSUE TITLE
Bulleted list function leaves unequal spaces

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#418] opened 2020-02-12 11:55 UTC
**What is the problem?**
Bulleted list function leaves unequal spaces. User case: writing text, pressing enter, pressing bulleted list function and writing on the 1 row; and when pressing enter again and starting to write the 2 row, unequal spaces between the bullet and text is shown (in row 1 and row 2). 

![Bullets](https://user-images.githubusercontent.com/45175679/74332456-6b625780-4d9e-11ea-9c7b-820cf1b3e27d.png)

**Why is this a problem?**
User must delete spaces every time when creating bulleted lists. 

**Possible solution.**
Bulleted list rows start at equal distance.

**Comment by loorm** [comment] 2020-02-25 11:49
Triage 18: we know, that occasionally these issues occur, but we cannot reproduce. If you open up a new topic and create a bulleted list, it works. Even much larger web text editors have similar issues. This is partially down to HTML specification. Blocking issue for now.

**Comment by KatiVellak** [comment] 2020-04-10 14:57
Legally reviewed, no impact.

**Comment by loorm** [comment] 2020-05-26 11:31
This seems to be working fine in newer versions of Etherpad. Closing issue.

**Closed as completed by loorm** 2020-05-26 11:31 UTC
Labels: blocked
