### ISSUE TITLE
(my/topics/:topicId & my/groups/.groupId) filter with no values displays as user has no topics/groups

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe-old#143] opened 2018-12-18 23:07 UTC
When user filters his/hers topics/groups in dashboard, if no results are returned, whole content are is covered by a message `You have not participated in a topic yet. Try it, it’s really cool!` and link to create a topic is displayed. There should probably be separate loading of topic with id in URL and topics in the list

**Comment by loorm** [comment] 2020-05-27 14:16
@ilmartyrk is this issue a duplicate of #293?

**Comment by loorm** [comment] 2021-07-27 09:08
Triage 42. This has been solved in another issue. Closing this issue.

**Closed as completed by loorm** 2021-07-27 09:08 UTC
Labels: UX
