### ISSUE TITLE
Typing bug when editing topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#437] opened 2020-03-16 14:47 UTC
**What is the problem?**
Twice while I was editing the COS 'Hi There!' instructions topic there was a bug with the typing. Suddenly I couldn't type in any spaces between words for just a select few word, which were all clumped together, as shown below in the screenshots - 'whichyouarean' and 'ofthescreen'. I kept deleting and trying again and the same words would always be joined together. (And I checked my typing in a Word document - it wasn't my space bar malfunctioning, it only happened in the COS topic). 

It seemed to be happening when editing at the end of one line which ran over to the beginning of the next line, if that helps. To overcome the problem the first time I had to copy and paste the text with spaces already written from the Word doc into the topic. And the second time I typed it with the words all joined together, then clicked back into the place where the space should be, after I had written the words, and it then did let me add the spaces in. 

![image](https://user-images.githubusercontent.com/61320526/76769380-51000d00-6794-11ea-970c-f3973cb42bf9.png)

![image](https://user-images.githubusercontent.com/61320526/76769397-55c4c100-6794-11ea-8602-03532f36af08.png)

**Why is this a problem?**
It's a usability issue. 

**Possible solution.**
Fixing the bug - making sure spaces can always be typed.

**Comment by loorm** [comment] 2020-04-29 12:09
Triage 20 - need to get an exact reproduction. @loorm will do. Prioritize after that.

**Comment by loorm** [comment] 2020-05-05 09:36
@ilmartyrk I have an exact reproduction.
1. Open up a new topic.
2. Write about one and a half lines of normal text.
3. Move cursor to the start of 2nd line.
4. Attempt to type.

The space at the end of line 1 will automatically disappear. The last word of the 1st line and the first word of the 2nd line will be merged together. You will end up typing in the centre of the newly formed superword.

**Comment by KatiVellak** [comment] 2020-05-22 12:18
Legally reviewed, no impact.

**Comment by ilmartyrk** [comment] 2020-05-27 09:09
Just for info: 
When just typing without etherpad counts line by characters in one p. That means visually for user it could be 3 lines of text, but inside html it is one block. Still it does some magic to understand if text is visually too on different lines. I traced it down to `etherpad-lite/src/static/js/ace2_inner.js` in `getLineAndCharForPoint` is the place where it shows the position of carret and where I found the wrong positioning (It displayed the point for the carret at the beginning of new line as it was at the end of the previous line, it also ignored the last character on previous line) so new text entered was appended to the previous line end not as the new text in new line, but still it somehow merged two texts together. I believe the issue has got something to do with this [multiple text nodes in html element](https://stackoverflow.com/questions/29245503/multiple-text-nodes-in-a-single-element). But I have not managed to pinpoint the exact location where to check if this is true or not.

**Comment by ilmartyrk** [comment] 2020-05-27 10:32
Seems to be related to this https://github.com/ether/etherpad-lite/issues/3087 as same thing is happening on our pad too. Last charater of a line is skipped when using arrow keys

**Comment by ilmartyrk** [comment] 2020-05-27 20:12
https://github.com/ether/etherpad-lite/pull/3831 Fixes the issue

**Closed as completed** 2020-05-28 10:00 UTC
Labels: bug, etherpad

**Comment by loorm** [comment] 2020-05-28 10:13
Tested. It works, but only for the first time. Every consecutive edit attempt after that still results in the error. Screencast here https://drive.google.com/file/d/1dnWfohDy-S3D6jIsUqJeROee0X4UK7gj/view?usp=sharing

**Comment by ilmartyrk** [comment] 2020-05-28 10:34
@loorm try disabling browser cache. Etherpad is hard to update, as it sits inside iframe so Shift+F5 don't work

**Comment by loorm** [comment] 2020-05-28 13:50
Gotcha. Disable browser cache worked. Tried all sort fo tricks to fool Etherpad back into old bad habits, but to no avail.

Tested. Confirmed working.
