### ISSUE TITLE
Add secret voting option to voting system

### ISSUE THREAD

**Issue by liinaguiter** [citizenos/citizenos-fe-old#691] opened 2021-04-20 10:29 UTC
**What is the user story?**
The NGO law in Estonia requires certain votings to be 100% secret, but right now the admin of the topic sees who voted and how they voted in the resulting document. This can create negative feelings and some NGO choose to do the secret voting 100% secret as is required by the law because their members request it. During a physical vote, the ballots are hand-written, but otherwise completely anonymous. They are counted, the result is signed by the required members and then the ballots are thrown away - they are not kept and the result cannot be changed afterwards. 

**What is the requested feature?**
Create a 'secret voting', where the results fail only includes how many votes were given for each option. 

**Additional information.**
Request comes from potential user Rafael Milerman. He is a director of the board of Eesti Leader Liit https://leaderliit.eu/meist/juhatus/ and believes this feature will prompt many NGO's to do their general meetings on COS. General meetings need to be held in an NGO every 3-5 years.

**Comment by loorm** [comment] 2021-04-28 13:27
There is nothing in NGO law (mittetulundusühingute seadus) requiring a secret vote. Any organisation, NGO or otherwise, can put a secret vote requirement in their own articles of association. So this is a valid use case, but the reasoning provided above is partially incorrect.

**Comment by tiblu** [comment] 2021-04-28 13:32
From @liinaguiter  in Slack on how the vote works in real life:
> How it works right now, with physical voting, is that the ballots are anonymous and hand-written. They are counted and the result is written down in a memo. That memo is signed by the required amount of members (not required to be signed by everyone). Then the ballots are thrown away. (edited)

**Comment by loorm** [comment] 2021-04-29 09:43
Triage 36. Accepted. We have added this to the "Advanced voting procedures" user epic. It needs some firther thinking about how to display the signed voting results. It is coming up in the Big Picture Board, until then the issue is temporarily blocked.

**Comment by liinaguiter** [comment] 2021-05-03 16:14
Here is an update on the laws of NGO (virtual) meetings in Estonia. There are also FAQ and one of the questions is about secret voting. https://heakodanik.ee/uudised/puust-ja-punaseks-kuidas-edaspidi-uldkoosolekuid-korraldada/

**Comment by tiblu** [comment] 2021-05-17 09:26
@loorm Moving this to "In preparation". If we added this to the "Advanced voting procedures", do we keep this task at all?

**Comment by loorm** [comment] 2021-07-13 06:53
> @loorm Moving this to "In preparation". If we added this to the "Advanced voting procedures", do we keep this task at all?

No. Closing the issue. It's in the epic.

**Closed as completed by loorm** 2021-07-13 06:53 UTC
Labels: blocked, feature
