### ISSUE TITLE
Folder system in groups

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#663] opened 2021-03-23 10:42 UTC
**What is the user story?**
User wants to separate topics in the group, e.g. in general meetings there are 3-5 topics where members input/voting is expected and it is difficult to separate the topics valid for the latest meeting. To search for topics, the user needs to know the topic title or keywords, but sometimes does not.

<img width="261" alt="Folders" src="https://user-images.githubusercontent.com/45175679/112134206-27fb2f00-8bd5-11eb-9b95-3ac6f3c393ff.png">

**What is the requested feature?**
 A folder system would help categorize and divide topics into folders.  

**Additional information.**
N/A

**Comment by loorm** [comment] 2021-04-28 11:00
Triage 36. Duplicate of #238. Closing issue.

**Closed as completed by loorm** 2021-04-28 11:00 UTC
Labels: duplicate, feature
