### ISSUE TITLE
Opening Help in non-English causes UI language to switch

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe-old#493] opened 2020-05-12 10:44 UTC
**What is the problem?**
Visiting Help topic causes UI language to switch.

How to reproduce:
- open http://app.citizenos.com/
- switch the UI language to any (other) language in which Help exists (RU, ET, EN)
- log in to your account
- open Help topic from the front page
= UI gets switched to another language (though Help itself stays in the originally intended language)

<img width="1438" alt="Screenshot 2020-05-12 at 13 42 26" src="https://user-images.githubusercontent.com/34126353/81674845-82c0e780-9456-11ea-883f-794670a68c56.png">

I've reproduced this in Safari and Chrome several times, got switched from Russian to English 4x and from Estonian to Russian 1x.

**Why is this a problem?**
Once user selects a language, they should stay within the same language UI. It's confusing to be thrown into a random other language UI.

**Comment by loorm** [comment] 2020-05-19 10:13
Assigning to Triage.

**Comment by loorm** [comment] 2020-05-25 08:40
Triage 22. Could not reproduce. Followed the instructions point by point.

**Closed as completed by loorm** 2020-05-25 08:40 UTC
Labels: bug

**Comment by KatiVellak** [comment] 2020-05-25 11:49
Legally reviewed, no impact.
