### ISSUE TITLE
Multiple-choice voting

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe-old#413] opened 2020-02-10 16:44 UTC
**What is the problem?**
Citizen OS supports single-choice voting, but in many user cases (selecting board members or representatives) multiple-choice voting is required.  

**Why is this a problem?**
People and organizations that need to organize multiple-choice voting, cannot use Citizen OS and we lose users.

**Possible solution.**
Enable multiple-choice voting in Citizen OS platform.

**Comment by loorm** [comment] 2020-02-25 11:01
Triage 18: moving back to in prep. Need a proper user story.

**Comment by ottomattas** [comment] 2020-03-24 08:15
I have a user story @loorm :
We are holding an election for our Workers Council. There are six candidates running for three positions on the council. Every worker in the company will get three votes (per position) to cast. In the end, top 3 candidates are elected based on all the cast votes.
Working around the limitation by creating three identical topics will not work as the voter will be able to cast all three votes to one candidate which is not allowed.

We are actually looking to implement the solution on-prem for multiple purposes and this is currently the show-stopper. I see that [citizenos-api](https://api.citizenos.com/documentation/#/vote/createTopicVote) supports `minChoices`/`maxChoices` in creating the voting which suggests that only the front end application needs development in this regard. I hope this enhancement can be implemented in the foreseeable future.

**Comment by tiblu** [comment] 2020-03-24 12:08
@ottomattas @loorm Created an investigation task to find out and describe what's the required effort of implementing multiple choice voting in the API - https://github.com/citizenos/citizenos-fe/issues/443. The idea is to describe it so, that IF we do not have our 1.5 developer time for it, maybe @ottomattas or other OSS contributors have time to implement.
What next? This investigation task will be prioritized ASAP and we'll let you know when we're going to execute. In our chats we have the vibe of high priority.

**Comment by tiblu** [comment] 2020-03-24 12:21
@ottomattas On my table now, working on it today and tomorrow - https://github.com/citizenos/citizenos-fe/issues/443

**Comment by tiblu** [comment] 2020-04-21 11:26
@kevincrepin We need help with the multiple-choice UX.

New stuff that comes along with multiple choice:

* In vote settings we have to have ability to choose multiple-choice.
* In multiple choice User can configure max and min votes that can be chosen at a time. Max and min can be the same number.
...

**Comment by kevincrepin** [comment] 2020-04-22 08:43
Added on Invision. Also updated how the voting choice selection is visualised since we now have this situation of single choice and multiple choice we need to differentiate this clearly. Also made it generally clearer which ones are selected compared to previously.

**Setting up a voting system:** 
https://projects.invisionapp.com/d/main#/console/9829159/414654327/preview
User has a plus/minus box that is constrained by the min and max amount. This way we make sure they don't fill in a random nr just to be punished for not knowing there's a limit.

**Multi choice voting empty state:**
https://projects.invisionapp.com/d/main#/console/9829159/414654328/preview
**Multi choice voting selected:**
https://projects.invisionapp.com/d/main#/console/9829159/414654329/preview
Updated the general look of choices so it's clearer which ones are selected and which aren't.

**Multi choice voting ended:**
https://projects.invisionapp.com/d/main#/console/9829159/414654330/preview
Made this clearer as well. Your vote is separated from the rest of the options to make it very understandable which one you chose.


**Single choice voting selected:**
https://projects.invisionapp.com/d/main#/console/9829159/414654331/preview
Just a reference for the "regular vote" how this should look now.

**Single choice voting ended:**
https://projects.invisionapp.com/d/main#/console/9829159/414654332/preview
Reference for single choice vote ending

**Comment by tiblu** [comment] 2020-04-22 12:34
@kevincrepin API supports min and max number of votes. That is, you can say "A User can vote for up-to 3, but not less than 2 options". On your designs, the max and min are always equal.
BUT, that said, I'm not sure there is really a need for such votes AND it would complicate the UX. I'm OK if it stays max===min.

@loorm Any comments on the screens and the implementation?

**Comment by tiblu** [comment] 2020-04-29 12:23
@loorm Triage 20 - promised to give input.

**Comment by loorm** [comment] 2020-04-29 12:29
Triage 20 - @loorm to review visuals.

**Comment by loorm** [comment] 2020-05-05 10:39
@tiblu @kevincrepin I reviewed the visuals.. They definitely add clarity. Found a few things, though.

The terminology is incompatible with the way we currently use terms in app. We say "voting", visuals often say "signing" instead etc. But this is irrelevant., we can fix it app side, no need to change visuals.

Also, there are links and options in the visuals that I'm not sure we have back end code for, like "View who has voted". or "End once all votes are in". But this is also irrelevant.

Based on the visuals, I don't know what happens, when max 2 choices are allowed and I have chosen 2 already. Are the rest locked or greyed out or are they unchecked the instant I check them or does it simply uncheck a random previous choice when I checkmark a third option? I believe this to be relevant.

Also, based on the visuals, it was not immediately clear, what the vote changing flow looks like. Once I have cast my vote, the visual makes it much more clear than before, which option I chose. I like the two-way split. But how do I change it? Where do I click? There are no more checkmarks... As the app currently works, when I want to change, I simply click on another option. In the visuals, there's an "edit vote" link on the right. I believe this also to be relevant.

**Comment by kevincrepin** [comment] 2020-05-06 11:02
Good points. Will explain, feel free to poke holes in it :)

The multiple choice works as regular checkmarks in that sense that in the scenario you described you have to uncheck one choice in order to "open up"/not be faded out the other choices again. 
For the single choice it works as a radio button: only one choice is available. This is also why unlike in the multiple choice, the unselected radiobutton is not faded out. You can choose freely any one option, there are no restrictions.

It would be helpful to state these "logic rules" also in the text maybe?

About the changing flow: These screens https://projects.invisionapp.com/d/main#/console/9829159/414654330/preview and https://projects.invisionapp.com/d/main#/console/9829159/414654332/preview only show once the voting has ended. Before this time, the screens remain these: https://projects.invisionapp.com/d/main#/console/9829159/414654329/preview and https://projects.invisionapp.com/d/main#/console/9829159/414654332/preview and thus editable.

The "edit vote" on the right is, at least in my, only available for the vote system creator. Although in this screen it should not be there in any case, because voting systems can't b changed anymore after creation, right? This function visible here might just be part of the old designs, better to ignore this.

**Comment by loorm** [comment] 2020-05-11 08:32
Triage 21. Needs input from @loorm. Moved to "In prep".

**Comment by loorm** [comment] 2020-05-11 10:40
@kevincrepin 

> Although in this screen it should not be there in any case, because voting systems can't b changed anymore after creation, right?

Right.

One last thing. What is the equivalent of the screenshot below in multiple-choice voting? Because on this screen (https://projects.invisionapp.com/d/main#/console/9829159/414654329/preview) there is no indication, that I have already sent in my votes.

![Capture_vote_done](https://user-images.githubusercontent.com/22661743/81552875-eda5ec00-938c-11ea-97ba-317a56c449b1.JPG)

**Comment by kevincrepin** [comment] 2020-05-13 13:52
This screen: https://projects.invisionapp.com/d/main#/console/9829159/414654330/preview
But I'm correct when I say this only shows after the voting deadline has been reached or the creator closes the vote, right? Before that I can always still change my vote.

**Comment by loorm** [comment] 2020-05-19 10:21
No. This appears as soon as you have voted. If you later (while voting is still open) decide to change your vote, you can download your updated vote. The container will indicate the date and time.

**Comment by loorm** [comment] 2020-05-19 10:23
Re-assigning for Triage.

**Comment by kevincrepin** [comment] 2020-05-19 11:18
One issue is that with multiple choice voting when does it go to that screen? There is no CTA now that says "submit your vote" and then leads you to this screen. Currently it works ok, because there is no multiple choice voting and every vote can trigger a refresh, but it's also not very clear that you can still change your vote...

I would suggest the following:

1: https://projects.invisionapp.com/d/main#/console/9829159/418246139/preview
2: https://projects.invisionapp.com/d/main#/console/9829159/418246140/preview
Choose & select your vote. Then press "submit your vote"

3. https://projects.invisionapp.com/d/main#/console/9829159/418246141/preview
Your vote is registered, but the deadline is not met, or it's not closed or whatever the parameter is.

4. https://projects.invisionapp.com/d/main#/console/9829159/418246142/preview
Voting has ended and you can see the full results. To discuss: Can you also in the UI still see more clearly what you voted? Now it is this green indication but that's pretty vague as well.

**Comment by loorm** [comment] 2020-05-20 06:46
Whatever you decide is more suitable, @kevincrepin. Just please make sure, that we have a consistent user experience across all voting methods (regular / custom / multiple choise, secure and social id, delegated and direct etc).

**Comment by kevincrepin** [comment] 2020-05-20 09:33
@loorm @tiblu 

Bigger things popped up when dealing with the delegation flow. Please check below.

Worked out additional flows, including how to show delegation. Also made minor adjustment on how to show which type of voting system you have selected.

Create voting system - custom:
https://projects.invisionapp.com/d/main#/console/9829159/414654327/preview
Cast your vote: 
https://projects.invisionapp.com/d/main#/console/9829159/414654328/preview
Selection made:
https://projects.invisionapp.com/d/main#/console/9829159/414654329/preview
Vote submitted:
https://projects.invisionapp.com/d/main#/console/9829159/414654330/preview
Vote ended:
https://projects.invisionapp.com/d/main#/console/9829159/418412297/preview

Delegation:
https://projects.invisionapp.com/d/main#/console/9829159/418412298/preview
Delegation vote submitted:
https://projects.invisionapp.com/d/main#/console/9829159/418412300/preview
Vote ended:
https://projects.invisionapp.com/d/main#/console/9829159/418412299/preview

Create voting system - regular (single choice):
https://projects.invisionapp.com/d/main#/console/9829159/418412301/preview
Cast your vote:
https://projects.invisionapp.com/d/main#/console/9829159/418412302/preview
Selection made:
https://projects.invisionapp.com/d/main#/console/9829159/414654331/preview
Vote submitted:
https://projects.invisionapp.com/d/main#/console/9829159/414654332/preview
Vote ended:
https://projects.invisionapp.com/d/main#/console/9829159/418412303/preview

If I have been delegated to vote for others:
https://projects.invisionapp.com/d/main#/console/9829159/418424725/preview
We need to clearly warn people that they have been given rights to vote in names of others. Then we need to give them the voting options x the amount of delegate votes were given. Wat possible usecases can break this? What if you are delegated by 100 ppl. Should there be a bulk operation at one point? But you can still choose specific options separately for separate people? The variations of scenarios can be quite big.

Select votes in name of others: https://projects.invisionapp.com/d/main#/console/9829159/418424726/preview
Submit all votes in one go:
https://projects.invisionapp.com/d/main#/console/9829159/418424727/preview
Voting has ended:
https://projects.invisionapp.com/d/main#/console/9829159/418424724/preview


So when diving more deeply into the delegation flow I came onto a lot of issues in the current system. No mail was sent to Lydia when I delegated my vote to her. She didn't get any notification in the app, nor did she see any difference in the voting system. All of these issues should be addressed.

Couple questions that rose up:

1. If I am delegated, can I also ignore this? Am I obligated to vote for other people if I'm delegated.
2. Can I actually use other people's votes to screw up a voting? Is there any reason why we should allow users to use other people's votes for any choice other than what the user votes for? When talking about democracy then I would say yes, but on the other hand, is that how delegation works – I don't know.
3. Is there any point in time before the voting has ended that I can see how the person voted in my name? Or is this only after the voting has ended?
4. Unrelated to delegation: If I don't set a deadline for the voting, how do I close it then? I didn't see/find this. Must I send it to the Follow-up phase? This is not very clear either.

**Comment by loorm** [comment] 2020-05-20 12:04
There's more things in these design images, than the scope of this issue. It needs to be split into separate issues (like delegation indication). Will work on it. 

**Responses to @kevincrepin**
1. Yes, you can. No obligation.
2. Legally, without getting too technical, there's two main types of delegation. 
- "do exactly what I ask"
- "make whatever decision you think is best"

The first kind is not necessary online, because there is no physical participation requirement anyway. It was useful for meetings (like board meetings), where such delegation replaced actual physical presence, but everyone still made their own decisions.

In online environments, only the second kind makes sense. There are a few specific cases, like a very limited voting period and the person knows, that they are not able to be online in that period but they have a specific opinion. In such case it would make sense to delegate voting right to someone, who will vote on your behalf but for the exact option you specify. In most other cases you need the second kind of delegation. Therefore we have built only the second kind of delegation into Citizen OS so far, where the delegated vote(s) follows the vote of the voter themself.

3. Right now in Citizen OS you cannot see how they voted at all, neither during nor after the vote. I suppose you should not be able to see how they voted while voting is still open, because that would also give you information about how the person themself voted, that you delegated your vote to. And that's not a good thing at all. 

4.  You don't. It stays open until you move topic into follow-up. This is "by design". The limbo - where voting deadline has expired, but topic is still "In voting" status - is more problemativ. I think, ideally, once the deadlin expires, the topic should automatically be moved to "Follow-up" status. But that would mean monitoring expiry dates and running crontabs on server, which we have been avoiding so far.

**Comment by KatiVellak** [comment] 2020-05-22 11:50
Legally reviewed, no further comments.

**Comment by loorm** [comment] 2020-05-25 08:57
Triage 22. There are questions about necessity of a separate vote_submitted view. Otherwise, it's ready for dev. API side is ready and tested. UX needs to be done. Est dev time 40 hours.

**Comment by ilmartyrk** [comment] 2020-07-08 13:47
@loorm, as @tiblu  already has referred to in the past. The current design has only one selector for how many options user can select and by the current design it works in a way that the number inserted is the count of options user has to select, but our API actually supports minimum and maximum number for options for at least x but not more than y options. Should we stay with the fixed number for both or go with full implementation?

**Comment by ilmartyrk** [comment] 2020-07-28 06:50
I went with the full implementation and added another input, also found a small bug in API when creating user bdoc with multiple choices. https://github.com/citizenos/citizenos-fe/commit/6c7bc83efd5f44434d80afb3685d796cf7ca1433

**Closed as completed by ilmartyrk** 2020-07-28 06:50 UTC
Labels: feature
