### ISSUE TITLE
UX issue: joining topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#602] opened 2020-12-10 09:20 UTC
This has probably been raised before but I will add it here just in case. When you are invited to a topic it seems that it doesn't show up in "my topics" right away, you can only access it via the email invite? So for example today I knew Anett had recently invited me to a topic, but I couldn't find it in my topics. So I had to go back through my emails to find the invite, in order to access it. 

If this is correct, and the only way to access it is via the original email, then to improve the UX it would be best if the topic (perhaps with a 'join?' button, to give the choice of whether you join it or not) shows up in "my topics" automatically as soon as you have been invited.

**Comment by loorm** [comment] 2020-12-15 09:32
Triage 31. Somewhat confirmed. There is a way to join a topic you have been invited to from Activity Feed. The user need for a more intuitive approach (i.e. to have it under My Topics) is understandable, however, to achieve what looks like a small change, we would need a substantial amount of UX and API work behind the scenes. Perhaps this is an idea that we can implement when we revamp the UX on a larger scale.

**Comment by BeccaMelhuish** [comment] 2020-12-15 11:45
@loorm OK yes thanks for the reply! Good to know for the FAQs/Help Centre too - perhaps we can explain this in there in the meantime. But yes would be great to consider it with the bigger UX overhaul :)

**Comment by tiblu** [comment] 2021-03-22 12:11
@loorm In case of "wontfix", shall we close this issue?

**Comment by loorm** [comment] 2021-04-29 09:25
Triage 36. Reviewed. No change, please see comment from Dec 15 above. Closing issue.

**Closed as completed by loorm** 2021-04-29 09:25 UTC
Labels: enhancement, wontfix
