### ISSUE TITLE
Advertise Smart ID alongside with Mobiil-ID and ID-card

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-fe-old#412] opened 2020-02-10 16:07 UTC
**What?**

Basically add Smart ID signing/authentication method logo everywhere where there is Mobiil-ID/ ID-card logo.

Some of the places are Vote creation and voting screen.

![image](https://user-images.githubusercontent.com/7405383/74166963-27e9db00-4c30-11ea-8d4a-4f4103f5b92d.png)

**Comment by tiblu** [comment] 2020-02-10 16:09
@kevincrepin Can you provide us with suitable logo that would fit in the places in the issue description?

**Comment by kevincrepin** [comment] 2020-02-11 12:40
As Invision is in the process of a cleanup, I've attached the logos here.

Small is for:
![Screenshot 2020-02-11 at 14 11 30](https://user-images.githubusercontent.com/26792281/74237533-72c12c80-4cdc-11ea-8acd-1bab793ed789.png)

Big is for:
![Screenshot 2020-02-11 at 14 11 19](https://user-images.githubusercontent.com/26792281/74237539-7785e080-4cdc-11ea-821f-ad786afb50ac.png)


[id_logos.zip](https://github.com/citizenos/citizenos-fe/files/4185692/id_logos.zip)

**Comment by loorm** [comment] 2020-02-25 10:58
Triage 18: dev time ETA 2 hrs.

**Comment by ilmartyrk** [comment] 2020-03-06 11:23
@kevincrepin smart-id icons small and big are same size

**Comment by kevincrepin** [comment] 2020-03-13 08:19
@ilmartyrk seems so :) It's anyways the width only that changes, I think, because it otherwise wouldn't fit in the vote-creation block.

**Comment by ilmartyrk** [comment] 2020-03-16 22:56
Fixed by https://github.com/citizenos/citizenos-fe/commit/4411c5531461b33c30e2ffb1c91c4104aa80c0e6

**Closed as completed** 2020-03-16 22:55 UTC
Labels: enhancement

**Comment by KatiVellak** [comment] 2020-04-10 14:41
Legally reviewed, no impact.

**Comment by loorm** [comment] 2020-04-29 07:25
Tested. Confirmed working.
